### ISSUE TITLE
Note in docs that several of these features are available in newer Python

### ISSUE THREAD

**Issue by costrouc** [materialsvirtuallab/monty#31]
I was using Monty because it was included with pymatgen. However, I think it is important to note that some features of Monty are available in Python >=  2.6 with a slightly different api. I understand that this package is compatible with Python 2 and 3 which is currently an advantage. Especially in the scientific community.

For example:

 - Starting in 3.2, there is support for transparent archiving and unarchiving of files via `shutil`. This does much of `monty.shutil`.

 - Starting in 3.2, there is support for temporary directories using the with syntax. `tempfile.TemporaryDirectory`.  

- Starting in 2.6, there is support for number of cpus `multiprocessing.cpu_count()`

**Comment by shyuep** [comment]
Thanks for the note. Pymatgen supports both py27 and Py3k, which is why some Py3 functions are duplicated in monty. Essentially, these are backports of Py3k functionality. When Py3k becomes the only Py version in wide use, we will remove some of these monty features.

However, I think the functionality that you mention is different. 

1. The archiving operations of shutil creates tar archives. This is not always what you want (and not what we wanted for the specific use case in custodian where we gzip all the results of the run but wants to retain the ability to look into the files using zless). monty.shutil actually performs recursive gzipping or bzipping of individual files in the directory, not creating a tar archive. Pls let me know if this is not what you meant.

2. Yes, TemporaryDirectory is indeed a complete replacement for ScratchDir. ScratchDir will be moved in future.

3.  Yes, I know that multiprocessing.cpu_count usually works. In fact, if you look at the source code, that is the first method that is tried. Some linux OSes still ship with Python < 2.7 though. BUt this method will probably be removed in the near future.
