### ISSUE TITLE
Recent versions of Monty give an error when pulling wflows from FW db

### ISSUE THREAD

**Issue by fraricci** [materialsvirtuallab/monty#375]
Posting here an issue I'm having with retrieving some workflows from my Firework db 
whose culprit seems to be recent versions of Monty.

I added my wflows from my laptop with fireworks==2.0.2, monty==2022.3.12. 
Then on cori where I run them, I have fireworks==1.9.8 and monty==2021.3.3. 
Now, when I get them with wf = lpad.get_wf_by_fw_id(wf_id) on my laptop, **for some of them** I get the following error. 
AFAIU, this has something to do with monty recent versions. 
I tried all versions back to the 2021.6.10, and found the 2021.5.9 working again.

It can be annoying, since who installs new version of monty can get trouble in retrieving some 
wflows added with previous versions on monty.

I'm aware that the issue could just come from me mixing two different versions of monty to read/write into the DB.
But it might be still useful to understand what's the issue here.

[monty_firework_error.log](https://github.com/materialsvirtuallab/monty/files/8445701/monty_firework_error.log)

**Comment by munrojm** [comment]
I plan on taking a look at this soon.

**Comment by fraricci** [comment]
Cool, thanks. Let me know if you need some help debugging since I have the data who generate that error...

**Comment by munrojm** [comment]
The pydantic additions are important to the new API. They allow us to use MSONable pymatgen types directly in pydantic document models to define the API query schema. I will make this a priority and take a look today.

**Comment by munrojm** [comment]
Quick update. This appears to be due to an incompatibility with the output of a class wrapped with `@deprecated` from `monty.dev` and the call to `issubclass` used to determine if the class is a pydantic model. Working on a solution now.

**Comment by munrojm** [comment]
@shyuep  Okay, the real issue here is that decorating any class with `@deprecated` from `monty.dev` results in a perceived type of `<function __main__.deprecated.<locals>.wrap.<locals>.wrapped(*args, **kwargs)>`.  This does not allow functions like `hasattr` and `issubclass` to work correctly, resulting in the following important piece of code in the `process_decoded` function of `MontyDecoder` to be faulty:
https://github.com/materialsvirtuallab/monty/blob/0d8273fc966c2c86fbe14789fda0858546a58840/monty/json.py#L412-L415

No MSONable classes decorated with `@deprecated` will show as having a `from_dict` method, and checking if it is a subclass of `BaseModel` will just fail and throw the error shown in @fraricci's output. 

I have gone ahead and fixed this in https://github.com/materialsvirtuallab/monty/pull/400.

**Comment by shyuep** [comment]
Thanks.
